language: go
go:
  - 1.9
  - "1.10"
  - 1.11
  - 1.12
  - tip
before_install:
  - go get -v github.com/smartystreets/goconvey
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - bash travis/install_etcd.sh &
  - sleep 3
script:
  - go get -u ./...
  - goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN || go test -v

